favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.2903226
  brandStrength: 1
  rhythmicContrast: 0.6792115
  brandColors:
    - '#D05B1F'
    - '#D0C5B5'
    - '#1F1614'
    - '#6E7F9A'
    - '#FFFFFF'
  lightness: 0.6523297
typography_spectrum: 0.5
layout_spectrum: 0.5232975
analytics:
  twitter: null
  google: null
  facebook: null
name: The Gehmans
