name: TheGehmans
favicon: null
layout_spectrum: 1
typography_spectrum: 0.72339
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Rodney + Jodi Gehman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6e6e6'
    - '#ff0000'
    - '#27211d'
    - '#0073a5'
    - '#cd6d4b'
  brandStrength: 0.6875
  lightness: 0.609319
  saturation: 1
  rhythmicContrast: 1
purpose: []
