name: TheGehmans
favicon: null
layout_spectrum: 0.98649185243994
typography_spectrum: 0.9275767079088837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#808080'
    - '#afafaf'
    - '#823215'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
